### ISSUE TITLE
It takes time to close gateway

### ISSUE THREAD

**Issue by yoshiteru-imamura** [hyperledger/fabric-gateway-java#87]
There seems to be a 3 second wait on shutdown for managedchannel.
Therefore, the wait time increases with the number of peers.

Is there anything I can do to shorten the shutdown time?

Can you shorten the waiting time?

Gateway.close->NetworkImpl.close->Channel.shutdown...PeerEventServiceClient.shutdown->lchannel.shutdown().awaitTermination(3,TimeUnit.SECONDS)

**Comment by yoshiteru-imamura** [comment]
I appreciate your help.
The gateway.close is now faster.

gateway.close(boolean force)
or
It would be even effective if you could release a version where we can select true or false in the config.properties setting.

Best regards,

**Comment by bestbeforetoday** [comment]
Good to hear that helped!

It would not be difficult to implement a configuration a setting to set (or remove) the default shutdown timeout. However, this would still leave users with a (perhaps unexpected) shutdown delay by default, and having to go hunting for that setting.

An alternative might be to just change the behaviour of `Gateway.close()` so that it forcefully closes the underlying Channel. The difference is that it would no longer wait for any in-flight gRPC invocations to complete. I suspect any in-flight invocations are likely to be persistent event streaming connections that we don't need to wait for and, if the application is calling close(), it likely knows there are no in-flight invocations that it cares about.

What do you think about changing the Gateway.close() behaviour?

**Comment by yoshiteru-imamura** [comment]
Hi. bestbeforetoday.

May I change the source code?

Can you please tell me the procedure for changing the source code?

**Comment by krishan31** [comment]
@bestbeforetoday , hey we are facing one issue in our fabric network

**Comment by bestbeforetoday** [comment]
@krishan31 The situation you are describing is not related to this issue. Please use [Discussions](https://github.com/hyperledger/fabric-gateway-java/discussions) for questions, or raise a separate [issue](https://github.com/hyperledger/fabric-gateway-java/issues) for potentials bugs or feature suggestions.

You should definitely not close your Gateway instance on every transaction. Creating and using a new Gateway instance typically requires several gRPC network connections to be established, which are then all closed when you close the Gateway instance. Creating and discarding network connections on every transaction is expensive. You should aim to reuse a single Gateway instance for all interactions from a given client identity.

The newer [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/) (for Fabric v2.4+) dramatically improves this area by allowing you to use a single gRPC connection for all interactions with Fabric, regardless of the number of client identities you are using to transact, as described in the [migration guide](https://hyperledger.github.io/fabric-gateway/migration#grpc-connections).

If you can use Fabric v2.4 or later, you should use the [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/).
